### ISSUE TITLE
can you run ADPICam IOC inside a docker?

### ISSUE THREAD

**Issue by LeeYangLBLBCS** [prjemian/epics-docker#67]
I can start IOC with ADPICam (https://github.com/areaDetector/ADPICam) using my new Princeton Instrument PICam camera MTE3.
However, when I tried to run the same IOC inside a docker, the camera can be found.
Has anyone succeeded running docker with this IOC?
I suspect the problem is caused by the PICam driver's requirement to run as root.
Nonethless, being root didn't help either.
Any idea/help would be appreciated.

**Comment by prjemian** [comment]
I am not aware of others using this docker for the ADPICam.  Might be good to ask EPICS tech-talk as well.

As far as I recall, the IOC runs as root in the container.

How does the IOC talk with the camera?  If it communicates using network sockets, you might need to start the docker container with an additional port specification for this communication.

**Comment by LeeYangLBLBCS** [comment]
communication is via USB.
yes, I know the user inside docker is root.
I also tried various parameters in "docker run " ... to act as root when docker starts.
such as docker run -it --previleged --asuser 0 , etc.
The camera can not be found in all cases.
I'll post on tech-talk.
thanks for  your help.
